#!/bin/bash
# Fetches API keys from GCP Secret Manager and writes to .env.local
# Run before starting dev server: ./scripts/load-secrets.sh && npm run dev

set -e

PROJECT_ID="flash-clover-464719-g1"
ENV_FILE=".env.local"

echo "🔐 Fetching secrets from GCP Secret Manager..."

# Fetch Gemini API Key
GEMINI_KEY=$(gcloud secrets versions access latest --secret="Google_API_Key" --project="$PROJECT_ID" 2>/dev/null)

if [ -z "$GEMINI_KEY" ]; then
    echo "❌ Failed to fetch GEMINI_API_KEY"
    exit 1
fi

# Write to .env.local
cat > "$ENV_FILE" << EOF
# Auto-generated by scripts/load-secrets.sh
# Do NOT commit this file
GEMINI_API_KEY=$GEMINI_KEY
EOF

echo "✅ Secrets written to $ENV_FILE"
echo "🚀 You can now run: npm run dev"
