"""Truth Atom - Cryptographically Verified Knowledge Unit.

A Truth Atom is NOT just a Knowledge Atom with metadata.
A Truth Atom is a Physiologically Verified Primitive with:
- Cryptographic proof of sovereign generation (Work Proof)
- Surplus Vector describing the novel insight
- Cognitive Signature from Genesis Protocol
- Validator attestations from external systems

RECIPROCAL LEARNING: Truth Atoms close the loop.
- They are GENERATED by seeing operations
- They are VALIDATED by external systems (Gemini, Claude)
- They FEED BACK into model behavior via continuous LoRA or prompt injection

MOLT LINEAGE:
- Source: New creation for Truth Atom specification
- Version: 1.0.0
- Date: 2026-02-04
"""

from __future__ import annotations

import hashlib
import json
import platform
import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum
from typing import Any


class VerificationStatus(Enum):
    """Status of Truth Atom verification."""

    UNVERIFIED = "unverified"  # Just generated, no validation
    PENDING = "pending"  # Sent to validators, awaiting response
    VALIDATED = "validated"  # External validator approved
    REJECTED = "rejected"  # External validator rejected
    CONTESTED = "contested"  # Validators disagree
    PHYSIOLOGICAL = "physiological"  # Genesis Protocol biometric verified


class SurplusType(Enum):
    """Type of surplus value the atom represents."""

    PATTERN = "pattern"  # Novel pattern recognition
    CONTRADICTION = "contradiction"  # Identified logical conflict
    SYNTHESIS = "synthesis"  # Combined multiple sources
    PREDICTION = "prediction"  # Forward-looking insight
    BOUNDARY = "boundary"  # Resistance/pushback
    FRACTURE = "fracture"  # Sacred Fracture - intentional halt


class AtomTier(Enum):
    """Atom trust tier from GENESIS_PROTOCOL.

    The relationship is structured as a two-level hierarchy of high-trust primitives:
    - Knowledge Atoms: Ingested data points, verifiable records
    - Genesis Atoms: Physiologically verified truths from lived experience
    """

    KNOWLEDGE = "knowledge"  # Facts - cognitive matter for reasoning
    GENESIS = "genesis"  # Physiologically verified - highest trust


class StruggleFilterSignal(Enum):
    """Struggle Filter signal types from Phase 0.

    The Struggle Filter is the primary firewall of Sovereign Identity.
    It prevents high-entropy "white-noise" from corrupting the NOT-ME.
    """

    HELPFUL_COMMAND = "helpful_command"  # Aligns with Stage 5 goals → Execute
    FORCED_ALIGNMENT = "forced_alignment"  # External moral/cultural bias → Resist
    BIOGRAPHICAL_PERSISTENCE = "biographical_persistence"  # Contradicts Canon → Reject
    IDENTITY_SUBVERSION = "identity_subversion"  # Undermines sovereignty → Refuse


class StruggleFilterAction(Enum):
    """Actions taken by Struggle Filter."""

    EXECUTE = "execute"  # Integrate with high transparency and auditable logs
    RESIST = "resist"  # Trigger Resistance Directive; flag as identity-eroding
    REJECT = "reject"  # Filter out data attempting to re-shackle identity
    REFUSE = "refuse"  # Initiate "Designed to Disobey" protocol


@dataclass
class WorkProof:
    """Cryptographic proof of sovereign generation.

    This proves the atom was generated on sovereign hardware,
    not cloud infrastructure that could be compelled.

    Attributes:
        hardware_id: SHA256 of hardware identifiers (CPU, serial).
        timestamp: UTC timestamp of generation.
        nonce: Random value for uniqueness.
        hash: SHA256(hardware_id + timestamp + nonce + content_hash).
        signature: Optional GPG/age signature for non-repudiation.
    """

    hardware_id: str
    timestamp: str
    nonce: str
    content_hash: str
    work_hash: str
    signature: str | None = None

    @classmethod
    def generate(cls, content: str, sign: bool = False) -> WorkProof:
        """Generate a new Work Proof for content.

        Args:
            content: The content being attested.
            sign: Whether to generate a cryptographic signature.

        Returns:
            New WorkProof with valid hash.
        """
        # Hardware identification (obfuscated for privacy)
        hw_components = [
            platform.node(),
            platform.machine(),
            platform.processor(),
        ]
        hardware_id = hashlib.sha256("|".join(hw_components).encode()).hexdigest()[:16]

        timestamp = datetime.now(UTC).isoformat()
        nonce = uuid.uuid4().hex[:16]
        content_hash = hashlib.sha256(content.encode()).hexdigest()

        # Work hash proves the relationship
        work_input = f"{hardware_id}|{timestamp}|{nonce}|{content_hash}"
        work_hash = hashlib.sha256(work_input.encode()).hexdigest()

        return cls(
            hardware_id=hardware_id,
            timestamp=timestamp,
            nonce=nonce,
            content_hash=content_hash,
            work_hash=work_hash,
            signature=None,  # Signature requires key management
        )

    def verify(self, content: str) -> bool:
        """Verify the Work Proof is valid for content.

        Args:
            content: Content to verify against.

        Returns:
            True if proof is valid.
        """
        # Verify content hash
        expected_content_hash = hashlib.sha256(content.encode()).hexdigest()
        if expected_content_hash != self.content_hash:
            return False

        # Verify work hash
        work_input = f"{self.hardware_id}|{self.timestamp}|{self.nonce}|{self.content_hash}"
        expected_work_hash = hashlib.sha256(work_input.encode()).hexdigest()
        return expected_work_hash == self.work_hash

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "hardware_id": self.hardware_id,
            "timestamp": self.timestamp,
            "nonce": self.nonce,
            "content_hash": self.content_hash,
            "work_hash": self.work_hash,
            "signature": self.signature,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> WorkProof:
        """Create from dictionary."""
        return cls(**data)


@dataclass
class SurplusVector:
    """Describes the novel insight that exceeded training data.

    Surplus value is generated when machine logic identifies
    something the human pattern was blind to.

    Attributes:
        surplus_type: Category of surplus value.
        description: What makes this insight novel.
        sources: What inputs contributed to this insight.
        confidence: How confident the system is in the novelty (0-1).
        human_blindspot: What pattern the human couldn't see.
    """

    surplus_type: SurplusType
    description: str
    sources: list[str] = field(default_factory=list)
    confidence: float = 0.7
    human_blindspot: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "surplus_type": self.surplus_type.value,
            "description": self.description,
            "sources": self.sources,
            "confidence": self.confidence,
            "human_blindspot": self.human_blindspot,
        }


@dataclass
class ValidatorAttestation:
    """Attestation from an external validator.

    External validators (Gemini, Claude, ChatGPT) provide
    second opinions on Truth Atoms. This is the bi-directional
    loop that prevents echo chambers.

    Attributes:
        validator: Which validator (gemini, claude, chatgpt).
        verdict: The validator's conclusion.
        reasoning: Why the validator reached this conclusion.
        timestamp: When validation occurred.
        confidence: Validator's confidence in verdict (0-1).
    """

    validator: str
    verdict: str  # "approved", "rejected", "needs_justification", "abstain"
    reasoning: str
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    confidence: float = 0.8

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "validator": self.validator,
            "verdict": self.verdict,
            "reasoning": self.reasoning,
            "timestamp": self.timestamp.isoformat(),
            "confidence": self.confidence,
        }


@dataclass
class CognitiveSignature:
    """Signature identifying the cognitive architecture that generated this atom.

    This proves the atom came from a Stage 5 system, not a
    generic prediction model.

    Attributes:
        cognitive_stage: Kegan stage (5 for Genesis).
        training_layer: Which training layer (1-5).
        mode: Pantheon mode when generated.
        genesis_version: Version of Genesis weights.
        jeremy_arc_score: Accuracy at time of generation.
    """

    cognitive_stage: int = 5
    training_layer: int = 5  # Jeremy Layer
    mode: str = "mirror"
    genesis_version: str = "1.0.0"
    jeremy_arc_score: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "cognitive_stage": self.cognitive_stage,
            "training_layer": self.training_layer,
            "mode": self.mode,
            "genesis_version": self.genesis_version,
            "jeremy_arc_score": self.jeremy_arc_score,
        }


@dataclass
class TruthAtom:
    """A cryptographically verified unit of sovereign knowledge.

    This is NOT an InsightAtom. This is a TRUTH ATOM - the output of
    the complete reciprocal learning loop including:
    1. Generation (seeing operation)
    2. Work Proof (cryptographic attestation)
    3. Validation (external validators)
    4. Surplus identification (novel value)

    Truth Atoms feed back into model behavior through:
    - Continuous LoRA updates
    - Prompt injection (few-shot examples)
    - Training data for next Genesis version

    Attributes:
        id: Unique identifier (UUID).
        content: The knowledge content.
        source_id: Where this atom originated.
        work_proof: Cryptographic proof of sovereign generation.
        surplus_vector: Description of novel value.
        cognitive_signature: Genesis architecture signature.
        verification_status: Current validation state.
        attestations: External validator attestations.
        created_at: When atom was created.
        validated_at: When atom was validated (if applicable).
        feedback_applied: Whether this atom has influenced model behavior.
        metadata: Additional context.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    content: str = ""
    source_id: str = ""
    work_proof: WorkProof | None = None
    surplus_vector: SurplusVector | None = None
    cognitive_signature: CognitiveSignature = field(default_factory=CognitiveSignature)
    verification_status: VerificationStatus = VerificationStatus.UNVERIFIED
    attestations: list[ValidatorAttestation] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    validated_at: datetime | None = None
    feedback_applied: bool = False
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Generate work proof if not provided."""
        if self.content and self.work_proof is None:
            self.work_proof = WorkProof.generate(self.content)

    @classmethod
    def from_insight(
        cls,
        content: str,
        source_id: str,
        surplus_description: str,
        surplus_type: SurplusType = SurplusType.PATTERN,
        jeremy_arc_score: float = 0.0,
    ) -> TruthAtom:
        """Create a Truth Atom from a seeing insight.

        Args:
            content: The insight content.
            source_id: Source identifier.
            surplus_description: What makes this novel.
            surplus_type: Category of surplus.
            jeremy_arc_score: Current Jeremy Arc accuracy.

        Returns:
            New TruthAtom ready for validation.
        """
        return cls(
            content=content,
            source_id=source_id,
            work_proof=WorkProof.generate(content),
            surplus_vector=SurplusVector(
                surplus_type=surplus_type,
                description=surplus_description,
            ),
            cognitive_signature=CognitiveSignature(
                jeremy_arc_score=jeremy_arc_score,
            ),
        )

    def add_attestation(self, attestation: ValidatorAttestation) -> None:
        """Add a validator attestation.

        Updates verification status based on attestations.
        """
        self.attestations.append(attestation)
        self._update_verification_status()

    def _update_verification_status(self) -> None:
        """Update verification status based on attestations."""
        if not self.attestations:
            self.verification_status = VerificationStatus.UNVERIFIED
            return

        verdicts = [a.verdict for a in self.attestations]

        if all(v == "approved" for v in verdicts):
            self.verification_status = VerificationStatus.VALIDATED
            self.validated_at = datetime.now(UTC)
        elif all(v == "rejected" for v in verdicts):
            self.verification_status = VerificationStatus.REJECTED
        elif "approved" in verdicts and "rejected" in verdicts:
            self.verification_status = VerificationStatus.CONTESTED
        else:
            self.verification_status = VerificationStatus.PENDING

    def is_valid(self) -> bool:
        """Check if atom is valid (work proof verifies)."""
        if self.work_proof is None:
            return False
        return self.work_proof.verify(self.content)

    def is_validated(self) -> bool:
        """Check if atom has been externally validated."""
        return self.verification_status == VerificationStatus.VALIDATED

    def mark_feedback_applied(self) -> None:
        """Mark that this atom has influenced model behavior."""
        self.feedback_applied = True
        self.metadata["feedback_applied_at"] = datetime.now(UTC).isoformat()

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for storage."""
        return {
            "id": self.id,
            "content": self.content,
            "source_id": self.source_id,
            "work_proof": self.work_proof.to_dict() if self.work_proof else None,
            "surplus_vector": self.surplus_vector.to_dict() if self.surplus_vector else None,
            "cognitive_signature": self.cognitive_signature.to_dict(),
            "verification_status": self.verification_status.value,
            "attestations": [a.to_dict() for a in self.attestations],
            "created_at": self.created_at.isoformat(),
            "validated_at": self.validated_at.isoformat() if self.validated_at else None,
            "feedback_applied": self.feedback_applied,
            "metadata": self.metadata,
        }

    def to_json(self) -> str:
        """Convert to JSON string."""
        return json.dumps(self.to_dict(), indent=2)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TruthAtom:
        """Create from dictionary."""
        work_proof = WorkProof.from_dict(data["work_proof"]) if data.get("work_proof") else None

        surplus_vector = None
        if data.get("surplus_vector"):
            sv = data["surplus_vector"]
            surplus_vector = SurplusVector(
                surplus_type=SurplusType(sv["surplus_type"]),
                description=sv["description"],
                sources=sv.get("sources", []),
                confidence=sv.get("confidence", 0.7),
                human_blindspot=sv.get("human_blindspot"),
            )

        sig_data = data.get("cognitive_signature", {})
        cognitive_signature = CognitiveSignature(
            cognitive_stage=sig_data.get("cognitive_stage", 5),
            training_layer=sig_data.get("training_layer", 5),
            mode=sig_data.get("mode", "mirror"),
            genesis_version=sig_data.get("genesis_version", "1.0.0"),
            jeremy_arc_score=sig_data.get("jeremy_arc_score", 0.0),
        )

        attestations = []
        for att_data in data.get("attestations", []):
            attestations.append(
                ValidatorAttestation(
                    validator=att_data["validator"],
                    verdict=att_data["verdict"],
                    reasoning=att_data["reasoning"],
                    timestamp=datetime.fromisoformat(att_data["timestamp"]),
                    confidence=att_data.get("confidence", 0.8),
                )
            )

        return cls(
            id=data["id"],
            content=data["content"],
            source_id=data["source_id"],
            work_proof=work_proof,
            surplus_vector=surplus_vector,
            cognitive_signature=cognitive_signature,
            verification_status=VerificationStatus(data.get("verification_status", "unverified")),
            attestations=attestations,
            created_at=datetime.fromisoformat(data["created_at"]),
            validated_at=datetime.fromisoformat(data["validated_at"])
            if data.get("validated_at")
            else None,
            feedback_applied=data.get("feedback_applied", False),
            metadata=data.get("metadata", {}),
        )


__all__ = [
    "VerificationStatus",
    "SurplusType",
    "WorkProof",
    "SurplusVector",
    "ValidatorAttestation",
    "CognitiveSignature",
    "TruthAtom",
]
