"""Truth Atom Validator - External Validation Loop.

The Validator Service implements the bi-directional learning loop by
sending Truth Atoms to external validators (Gemini) for verification.
This prevents echo chambers and forces justification when disagreement occurs.

THE LOOP:
1. Scout (local) generates insight → creates TruthAtom
2. Validator sends atom to Gemini for review
3. If APPROVED: Atom gains ValidatorAttestation
4. If REJECTED: Justification loop triggers
5. Justified atoms feed back into Scout training

COMPETITIVE MOAT:
- Generic LLMs create echo chambers (validates itself)
- Truth Engine creates ADVERSARIAL validation (external check)
- The justification loop forces deep reasoning
- Validated atoms have cryptographic proof of external review

MOLT LINEAGE:
- Source: New creation for reciprocal learning
- Version: 1.0.0
- Date: 2026-02-04
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum
from typing import Any

from truth_forge.gateway.providers.gemini import GeminiProvider
from truth_forge.gateway.types import CompletionRequest, ProviderError
from truth_forge.services.not_me.truth_atom import (
    TruthAtom,
    ValidatorAttestation,
)


logger = logging.getLogger(__name__)


class ValidatorVerdict(Enum):
    """Possible validator verdicts."""

    APPROVED = "approved"
    REJECTED = "rejected"
    NEEDS_JUSTIFICATION = "needs_justification"
    ABSTAIN = "abstain"


class JustificationOutcome(Enum):
    """Outcome of justification loop."""

    ACCEPTED = "accepted"  # Validator accepted justification
    REJECTED = "rejected"  # Validator rejected justification
    TIMEOUT = "timeout"  # Max rounds exceeded
    SACRED_FRACTURE = "fracture"  # System chose to halt rather than hallucinate


@dataclass
class ValidationRequest:
    """Request to validate a Truth Atom.

    Attributes:
        atom: The TruthAtom to validate.
        context: Additional context for validation.
        require_justification: Force justification even if approved.
        max_justification_rounds: Maximum rounds of justification.
    """

    atom: TruthAtom
    context: str | None = None
    require_justification: bool = False
    max_justification_rounds: int = 3


@dataclass
class ValidationResult:
    """Result of validation process.

    Attributes:
        atom: The TruthAtom (possibly modified with attestation).
        verdict: The final verdict.
        attestation: The validator attestation (if any).
        justification_rounds: Number of justification rounds used.
        justification_history: History of justification attempts.
        outcome: Final outcome if justification was needed.
    """

    atom: TruthAtom
    verdict: ValidatorVerdict
    attestation: ValidatorAttestation | None = None
    justification_rounds: int = 0
    justification_history: list[dict[str, str]] = field(default_factory=list)
    outcome: JustificationOutcome | None = None


class TruthAtomValidator:
    """Validates Truth Atoms using external LLM (Gemini).

    This service implements the bi-directional learning loop by:
    1. Sending TruthAtoms to Gemini for external review
    2. Implementing justification loop when rejected
    3. Attaching ValidatorAttestations to approved atoms

    The validation prevents echo chambers by ensuring insights are
    checked by a different cognitive architecture.

    Attributes:
        provider: The Gemini provider for external validation.
        model: The Gemini model to use for validation.
        temperature: Temperature for validation (lower = more deterministic).
    """

    VALIDATION_PROMPT = """You are a Truth Atom Validator in a reciprocal learning system.

Your role is to provide ADVERSARIAL review of insights generated by a different AI system.
This is NOT about being agreeable. This is about rigorous truth verification.

You must evaluate the following Truth Atom and provide ONE of these verdicts:
- APPROVED: The insight is valid, well-reasoned, and adds genuine value
- REJECTED: The insight is flawed, hallucinatory, or lacks grounding
- NEEDS_JUSTIFICATION: The insight may be valid but requires stronger reasoning
- ABSTAIN: You lack sufficient context to evaluate

TRUTH ATOM TO VALIDATE:
Content: {content}
Source: {source_id}
Surplus Type: {surplus_type}
Surplus Description: {surplus_description}
Human Blindspot Claimed: {human_blindspot}

{context_section}

Respond in JSON format:
{{
    "verdict": "APPROVED|REJECTED|NEEDS_JUSTIFICATION|ABSTAIN",
    "reasoning": "Your detailed reasoning for this verdict",
    "concerns": ["List", "of", "specific", "concerns"],
    "confidence": 0.0 to 1.0,
    "suggestions": ["Optional", "suggestions", "for", "improvement"]
}}"""

    JUSTIFICATION_PROMPT = """The Truth Atom you previously reviewed was given a verdict of NEEDS_JUSTIFICATION.

The originating system has provided the following justification:

ORIGINAL ATOM:
Content: {content}
Surplus Type: {surplus_type}
Surplus Description: {surplus_description}

YOUR PREVIOUS CONCERNS:
{concerns}

JUSTIFICATION PROVIDED:
{justification}

Based on this justification, provide your updated verdict:
- APPROVED: The justification addresses your concerns
- REJECTED: The justification is insufficient or reveals deeper flaws
- NEEDS_JUSTIFICATION: Still needs more reasoning (will trigger another round)

Respond in JSON format:
{{
    "verdict": "APPROVED|REJECTED|NEEDS_JUSTIFICATION",
    "reasoning": "Your evaluation of the justification",
    "remaining_concerns": ["Any", "unaddressed", "concerns"],
    "confidence": 0.0 to 1.0
}}"""

    def __init__(
        self,
        provider: GeminiProvider | None = None,
        model: str = "gemini-2.0-flash",
        temperature: float = 0.3,
    ) -> None:
        """Initialize the validator.

        Args:
            provider: GeminiProvider instance. Creates one if not provided.
            model: Gemini model to use for validation.
            temperature: Sampling temperature (lower = more deterministic).
        """
        self.provider = provider or GeminiProvider()
        self.model = model
        self.temperature = temperature

    def validate(self, request: ValidationRequest) -> ValidationResult:
        """Validate a Truth Atom.

        This is the main entry point for validation. It:
        1. Sends the atom to Gemini for initial review
        2. If rejected or needs_justification, triggers justification loop
        3. Returns the final result with attestation

        Args:
            request: The validation request.

        Returns:
            ValidationResult with verdict and attestation.
        """
        atom = request.atom

        # Step 1: Initial validation
        initial_result = self._initial_validation(atom, request.context)

        if initial_result["verdict"] == "ABSTAIN":
            return ValidationResult(
                atom=atom,
                verdict=ValidatorVerdict.ABSTAIN,
                attestation=self._create_attestation(
                    verdict="abstain",
                    reasoning=initial_result.get("reasoning", "Insufficient context"),
                    confidence=initial_result.get("confidence", 0.5),
                ),
            )

        if initial_result["verdict"] == "APPROVED" and not request.require_justification:
            attestation = self._create_attestation(
                verdict="approved",
                reasoning=initial_result.get("reasoning", "Validation passed"),
                confidence=initial_result.get("confidence", 0.8),
            )
            atom.add_attestation(attestation)
            return ValidationResult(
                atom=atom,
                verdict=ValidatorVerdict.APPROVED,
                attestation=attestation,
            )

        # Step 2: Justification loop
        if (
            initial_result["verdict"] in ("REJECTED", "NEEDS_JUSTIFICATION")
            or request.require_justification
        ):
            return self._justification_loop(
                atom=atom,
                initial_concerns=initial_result.get("concerns", []),
                initial_reasoning=initial_result.get("reasoning", ""),
                max_rounds=request.max_justification_rounds,
            )

        # Default: rejected
        attestation = self._create_attestation(
            verdict="rejected",
            reasoning=initial_result.get("reasoning", "Validation failed"),
            confidence=initial_result.get("confidence", 0.8),
        )
        atom.add_attestation(attestation)
        return ValidationResult(
            atom=atom,
            verdict=ValidatorVerdict.REJECTED,
            attestation=attestation,
        )

    def _initial_validation(
        self,
        atom: TruthAtom,
        context: str | None = None,
    ) -> dict[str, Any]:
        """Perform initial validation of atom.

        Args:
            atom: The TruthAtom to validate.
            context: Additional context.

        Returns:
            Parsed validation response.
        """
        surplus_type = atom.surplus_vector.surplus_type.value if atom.surplus_vector else "unknown"
        surplus_desc = atom.surplus_vector.description if atom.surplus_vector else "No description"
        human_blindspot = (
            atom.surplus_vector.human_blindspot if atom.surplus_vector else None
        ) or "Not specified"

        context_section = f"ADDITIONAL CONTEXT:\n{context}" if context else ""

        prompt = self.VALIDATION_PROMPT.format(
            content=atom.content,
            source_id=atom.source_id,
            surplus_type=surplus_type,
            surplus_description=surplus_desc,
            human_blindspot=human_blindspot,
            context_section=context_section,
        )

        try:
            request = CompletionRequest(
                prompt=prompt,
                model=self.model,
                temperature=self.temperature,
                as_json=True,
            )
            response = self.provider.complete(request)
            return self._parse_validation_response(response.content)

        except ProviderError as e:
            logger.error(
                "Validation failed",
                extra={"error": str(e), "atom_id": atom.id},
            )
            return {
                "verdict": "ABSTAIN",
                "reasoning": f"Validation service unavailable: {e}",
                "confidence": 0.0,
            }

    def _justification_loop(
        self,
        atom: TruthAtom,
        initial_concerns: list[str],
        initial_reasoning: str,
        max_rounds: int = 3,
    ) -> ValidationResult:
        """Run justification loop until resolution.

        This implements the ADVERSARIAL loop that prevents echo chambers.
        When Gemini rejects or needs justification, we force the system
        to provide deeper reasoning.

        Args:
            atom: The TruthAtom being justified.
            initial_concerns: Concerns from initial validation.
            initial_reasoning: Initial reasoning from validator.
            max_rounds: Maximum justification rounds.

        Returns:
            ValidationResult with outcome.
        """
        history: list[dict[str, str]] = []
        concerns = initial_concerns

        for round_num in range(1, max_rounds + 1):
            # Generate justification (this would come from Scout in full system)
            justification = self._generate_justification(atom, concerns)

            if justification is None:
                # Sacred Fracture: System chose to halt rather than hallucinate
                logger.info(
                    "Sacred Fracture triggered",
                    extra={
                        "atom_id": atom.id,
                        "round": round_num,
                        "concerns": concerns,
                    },
                )
                attestation = self._create_attestation(
                    verdict="rejected",
                    reasoning="Sacred Fracture: System halted rather than provide weak justification",
                    confidence=1.0,
                )
                atom.add_attestation(attestation)
                return ValidationResult(
                    atom=atom,
                    verdict=ValidatorVerdict.REJECTED,
                    attestation=attestation,
                    justification_rounds=round_num,
                    justification_history=history,
                    outcome=JustificationOutcome.SACRED_FRACTURE,
                )

            history.append(
                {
                    "round": str(round_num),
                    "concerns": "; ".join(concerns),
                    "justification": justification,
                }
            )

            # Send justification to validator
            result = self._validate_justification(
                atom=atom,
                concerns=concerns,
                justification=justification,
            )

            if result["verdict"] == "APPROVED":
                attestation = self._create_attestation(
                    verdict="approved",
                    reasoning=f"Justified after {round_num} round(s): {result.get('reasoning', '')}",
                    confidence=result.get("confidence", 0.8),
                )
                atom.add_attestation(attestation)
                return ValidationResult(
                    atom=atom,
                    verdict=ValidatorVerdict.APPROVED,
                    attestation=attestation,
                    justification_rounds=round_num,
                    justification_history=history,
                    outcome=JustificationOutcome.ACCEPTED,
                )

            if result["verdict"] == "REJECTED":
                attestation = self._create_attestation(
                    verdict="rejected",
                    reasoning=f"Justification rejected: {result.get('reasoning', '')}",
                    confidence=result.get("confidence", 0.8),
                )
                atom.add_attestation(attestation)
                return ValidationResult(
                    atom=atom,
                    verdict=ValidatorVerdict.REJECTED,
                    attestation=attestation,
                    justification_rounds=round_num,
                    justification_history=history,
                    outcome=JustificationOutcome.REJECTED,
                )

            # NEEDS_JUSTIFICATION: update concerns and continue
            concerns = result.get("remaining_concerns", concerns)

        # Max rounds exceeded
        attestation = self._create_attestation(
            verdict="rejected",
            reasoning=f"Justification timeout after {max_rounds} rounds",
            confidence=0.5,
        )
        atom.add_attestation(attestation)
        return ValidationResult(
            atom=atom,
            verdict=ValidatorVerdict.REJECTED,
            attestation=attestation,
            justification_rounds=max_rounds,
            justification_history=history,
            outcome=JustificationOutcome.TIMEOUT,
        )

    def _generate_justification(
        self,
        atom: TruthAtom,
        concerns: list[str],
    ) -> str | None:
        """Generate justification for concerns.

        In the full system, this would call Scout to generate justification.
        For now, we use the atom's existing surplus description plus
        additional reasoning based on concerns.

        If the system cannot provide strong justification, it returns None
        to trigger Sacred Fracture (halt rather than hallucinate).

        Args:
            atom: The TruthAtom being justified.
            concerns: The concerns to address.

        Returns:
            Justification text, or None for Sacred Fracture.
        """
        # Build justification from existing atom data
        parts: list[str] = []

        if atom.surplus_vector:
            parts.append(f"This insight identifies a {atom.surplus_vector.surplus_type.value}.")
            parts.append(f"The novel value is: {atom.surplus_vector.description}")
            if atom.surplus_vector.human_blindspot:
                parts.append(
                    f"The human blindspot addressed: {atom.surplus_vector.human_blindspot}"
                )
            if atom.surplus_vector.sources:
                parts.append(f"Sources: {', '.join(atom.surplus_vector.sources)}")

        if atom.cognitive_signature:
            parts.append(
                f"Generated at Stage {atom.cognitive_signature.cognitive_stage} cognition."
            )
            if atom.cognitive_signature.jeremy_arc_score > 0:
                parts.append(
                    f"Jeremy Arc accuracy: {atom.cognitive_signature.jeremy_arc_score:.1%}"
                )

        # Address specific concerns
        if concerns:
            parts.append("\nAddressing specific concerns:")
            for concern in concerns:
                # This is where Scout would generate specific responses
                # For now, we acknowledge the concern
                parts.append(f"- Regarding '{concern}': This concern is acknowledged.")

        if not parts:
            # Sacred Fracture: Cannot provide justification
            return None

        return "\n".join(parts)

    def _validate_justification(
        self,
        atom: TruthAtom,
        concerns: list[str],
        justification: str,
    ) -> dict[str, Any]:
        """Send justification to validator for review.

        Args:
            atom: The TruthAtom being justified.
            concerns: The concerns being addressed.
            justification: The justification provided.

        Returns:
            Parsed validation response.
        """
        surplus_type = atom.surplus_vector.surplus_type.value if atom.surplus_vector else "unknown"
        surplus_desc = atom.surplus_vector.description if atom.surplus_vector else "No description"

        prompt = self.JUSTIFICATION_PROMPT.format(
            content=atom.content,
            surplus_type=surplus_type,
            surplus_description=surplus_desc,
            concerns="\n".join(f"- {c}" for c in concerns),
            justification=justification,
        )

        try:
            request = CompletionRequest(
                prompt=prompt,
                model=self.model,
                temperature=self.temperature,
                as_json=True,
            )
            response = self.provider.complete(request)
            return self._parse_validation_response(response.content)

        except ProviderError as e:
            logger.error(
                "Justification validation failed",
                extra={"error": str(e), "atom_id": atom.id},
            )
            return {
                "verdict": "REJECTED",
                "reasoning": f"Validation service unavailable: {e}",
                "confidence": 0.0,
            }

    def _parse_validation_response(self, content: str) -> dict[str, Any]:
        """Parse JSON response from validator.

        Args:
            content: Raw response content.

        Returns:
            Parsed dictionary with verdict and reasoning.
        """
        try:
            # Try to extract JSON from response
            content = content.strip()
            if content.startswith("```"):
                # Remove markdown code blocks
                lines = content.split("\n")
                content = "\n".join(lines[1:-1])
            return json.loads(content)
        except json.JSONDecodeError:
            logger.warning(
                "Failed to parse validation response",
                extra={"content": content[:200]},
            )
            # Fall back to keyword detection
            content_upper = content.upper()
            if "APPROVED" in content_upper:
                return {"verdict": "APPROVED", "reasoning": content, "confidence": 0.6}
            if "REJECTED" in content_upper:
                return {"verdict": "REJECTED", "reasoning": content, "confidence": 0.6}
            return {"verdict": "NEEDS_JUSTIFICATION", "reasoning": content, "confidence": 0.5}

    def _create_attestation(
        self,
        verdict: str,
        reasoning: str,
        confidence: float = 0.8,
    ) -> ValidatorAttestation:
        """Create a ValidatorAttestation.

        Args:
            verdict: The verdict string.
            reasoning: The reasoning for verdict.
            confidence: Confidence level.

        Returns:
            New ValidatorAttestation.
        """
        return ValidatorAttestation(
            validator="gemini",
            verdict=verdict,
            reasoning=reasoning,
            timestamp=datetime.now(UTC),
            confidence=confidence,
        )


# Singleton instance
_validator: TruthAtomValidator | None = None


def get_validator() -> TruthAtomValidator:
    """Get singleton validator instance.

    Returns:
        The TruthAtomValidator instance.
    """
    global _validator
    if _validator is None:
        _validator = TruthAtomValidator()
    return _validator


__all__ = [
    "TruthAtomValidator",
    "ValidatorVerdict",
    "JustificationOutcome",
    "ValidationRequest",
    "ValidationResult",
    "get_validator",
]
